### ISSUE TITLE
panic: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ari-becker** [hashicorp/vault-secrets-operator#630]
**Describe the bug**
```
 2024-03-01T08:42:04Z    INFO    Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference    {"controller": "vaultpkisecret", "controllerGroup": "secrets.hashicorp.com", "controllerKind": "VaultPKISecret", "VaultPKISecret": {"name":"test","namespace":"test"}, "namespace": "test", "name": "test", "reconcileID": "eb7df11b-d6c6-42c0-8b72-70ed56cad585"}
 panic: runtime error: invalid memory address or nil pointer dereference [recovered]
     panic: runtime error: invalid memory address or nil pointer dereference
 [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1a2a5f2]
 
 goroutine 645 [running]:
 sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
     /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.1/pkg/internal/controller/controller.go:116 +0x1e5
 panic({0x1c568e0?, 0x34288c0?})
     /opt/hostedtoolcache/go/1.21.5/x64/src/runtime/panic.go:914 +0x21f
 github.com/hashicorp/vault-secrets-operator/internal/vault.UnmarshalPKIIssueResponse(0xc00060d360?)
     /home/runner/work/vault-secrets-operator/vault-secrets-operator/internal/vault/vault.go:23 +0x12
 github.com/hashicorp/vault-secrets-operator/controllers.(*VaultPKISecretReconciler).Reconcile(0xc000713030, {0x24561e8, 0xc001b0e150}, {{{0xc00214ad36, 0x9}, {0xc00214ad40, 0xe}}})
     /home/runner/work/vault-secrets-operator/vault-secrets-operator/controllers/vaultpkisecret_controller.go:190 +0x10bd
 sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x2459db0?, {0x24561e8?, 0xc001b0e150?}, {{{0xc00214ad36?, 0xb?}, {0xc00214ad40?, 0x0?}}})
     /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.1/pkg/internal/controller/controller.go:119 +0xb7
 sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0005beaa0, {0x2456220, 0xc0004638b0}, {0x1d19860?, 0xc001c4cde0?})
     /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.1/pkg/internal/controller/controller.go:316 +0x3cc
 sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0005beaa0, {0x2456220, 0xc0004638b0})
     /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.1/pkg/internal/controller/controller.go:266 +0x1af
 sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
     /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.1/pkg/internal/controller/controller.go:227 +0x79
 created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 111
     /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.1/pkg/internal/controller/controller.go:223 +0x565
```

**Environment**
* Kubernetes version: 
  * Distribution or cloud vendor (OpenShift, EKS, GKE, AKS, etc.): GKE
  * Other configuration options or runtime services (istio, etc.):
* vault-secrets-operator version: 0.5.1

**Comment by tvoran** [comment]
Hi @ari-becker, do you have an example VaultPKISecret spec that causes this?

**Comment by ari-becker** [comment]
@tvoran 

```yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultPKISecret
metadata:
  name: test
spec:
  vaultAuthRef: test
  namespace: "/"
  mount: example-com
  role: example-role
  commonName: test
  altNames:
    - test.example-kube-namespace
  destination:
    create: true
    name: test
```

@tvoran I read into the code of the `vault-secrets-operator` a bit, my guess is on line https://github.com/hashicorp/vault-secrets-operator/blob/f1b8cb5ae607321f347c8afc8435fe12841c044e/internal/vault/vault.go#L23 that `resp.Data` is `nil`, due to some kind of error in the response from Vault. But I'm not sure how to confirm that.
